--- 
title: "CYZ-SMAD4-m6A-demo"
author: "Dongjie Chen"
date: "`r Sys.Date()`"
output: pdf_document
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  This is a minimal example of using the bookdown package to write a book.
  set in the _output.yml file.
  The HTML output format for this example is bookdown::gitbook,
link-citations: yes
github-repo: "rstudio/bookdown-demo"
site: bookdown::bookdown_site
---


```{r,eval=FALSE,echo=FALSE}
bookdown::render_book('index.Rmd', 'bookdown::gitbook')
```



# About

**SMAD4/m6a项目-曹易之 **

* SMAD4突变/低表达与较高的m6a水平相关
* 参考文献：DOI: 10.1186/s12943-021-01408-5
* 数量： 2*(0.5 Figure) 
* 转录组水平
* 多数据集验证
* 如果突变做不出来，可以用突变+低表达
* m6a评分

**Palette**

* 三种颜色 (优先) ,前两种双色首选
#B71375
#FC4F00
#F79540

```{r,echo=FALSE,eval=FALSE}  
# dir.create('./Result/01-readme')

library(ggsci)
library(scales)
mypal <- c("#B71375","#F79540","#FC4F00")
png("./Result/01-readme/3_color.png",width = 4, height = 4,res = 1200,units = "in")
show_col(mypal, ncol = 3)
dev.off()
  
```




